'\" t
.\"
.pc
.TH AALINA 6 "2014-08-01" "1.0.0" "Aualé Manual"
.SH NAME
Aalina \- Oware Abapa game engine
.\" ********************************************************************
.SH SYNOPSIS
.B aalina
.\" ********************************************************************
.SH DESCRIPTION
.PP
.B Aalina
is a strong oware abapa playing program. It communicates with a Graphical User
Interface through an adapted version of the
.B "Universal Chess Interface"
protocol. This mancala engine is thus usually invoked by a GUI such as
.B Aualé,
which is the official interface for
.B Aalina.
.PP
Its features include:
.PP
* Plays mancala following the popular Abapa ruleset.
.br
* Includes an extensive opening book.
.br
* May use endgame databases to improve its strength.
.br
* Completely configurable through the UCI protocol.
.\" ********************************************************************
.SH AUTHOR
Joan Sala Soler (contact@joansala.com)
.\" ********************************************************************
.SH "SEE ALSO"
.BR auale (6)
